name: Auto Merge and Delete Branch on No Conflict

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  check-and-merge:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # Step 1: 使用 GitHub CLI 和 API 检查 PR 是否可合并
      - name: Check mergeability
        id: check-mergeable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # 获取PR的详细JSON信息，其中包含mergeable状态
          pr_info=$(gh pr view $PR_NUMBER --json mergeable)
          mergeable_status=$(echo $pr_info | jq -r '.mergeable')
          
          # 等待GitHub完成冲突检测（有时状态为null）
          counter=0
          while [[ "$mergeable_status" == "null" && $counter -lt 10 ]]; do
            echo "Waiting for mergeable status to be calculated... ($counter/10)"
            sleep 3
            pr_info=$(gh pr view $PR_NUMBER --json mergeable)
            mergeable_status=$(echo $pr_info | jq -r '.mergeable')
            ((counter++))
          done
          
          echo "Mergeable status: $mergeable_status"
          echo "mergeable=$mergeable_status" >> $GITHUB_OUTPUT

      # Step 2: 自动合并并删除分支
      - name: Merge PR and delete source branch
        if: steps.check-mergeable.outputs.mergeable == 'MERGEABLE'
        env:
          GH_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }} # 需要repo权限的PAT
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr merge $PR_NUMBER --squash --delete-branch

      # Step 3: 如果存在冲突，则添加评论
      - name: Comment if conflict exists
        if: steps.check-mergeable.outputs.mergeable == 'CONFLICTING'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ This PR has merge conflicts. Please resolve them before it can be merged.'
            })
